#+title: Projects
#+EXPORT_FILE_NAME: projects.html
#+OPTIONS: toc:nil html-postamble:nil html-preamble:nil title:nil html-style:nil
#+HTML_HEAD: <link rel="stylesheet" href="static/styles.css"></link>
#+BEGIN_EXPORT html
    <h3><a href="index.html">Dhruva Kashyap</a></h3>
    <div class="main">
      <h2>My Projects</h2>
      <br /><br />
      I've done many small projects throughout the years, here are a few that I really liked, in no particular order.
      <div class="pages">
          <h4>Garbage Collection in C++</h4>
        <p>
          Why would you want to do that? Is it even possible? Well, it is, kinda. Although it would go completely against many of the "philosophies" of
          C++, we were more concerned about whether we could, and not whether we should. This was a project we did for a course on Design Patterns.
          We ended up writing our own memory management system so that we could manage it ourselves. RAII, which I do not yet fully understand, helped us
          out too. There was a lot of template magic which I wrote in a dazed stupor which I have no recollection of.
          <a href="https://github.com/DhruvaKashyap/Garbage-Collection-in-Cpp">[Code]</a>
        </p>
          <h4>A JSON parser for C</h4>
        <p>
          I had finally understood pointers in C and decided to implement something that one could call "generic programming". It led to me reading about
          associative arrays from Perl and it finally lead to this JSON Parser in C.
          <a href="https://github.com/DhruvaKashyap/C-JSON-Parser">[Code]</a>
        </p>
          <h4>Imitation Learning on Enduro</h4>
        <p>
          Enduro was a racing game made for the Atari 2600. We were learning to use <a href="https://gym.openai.com/">OpenAI's Gym Environment</a> to
          demonstrate a project for a course on reinforcement Learning. What better way to spend our time than playing old Atari games?
          <a href="https://github.com/sumukhaithal6/Enduro-Imitation-Learning">[Code]</a>
        </p>
      </div>
      <br /><br />
    </div>
#+END_EXPORT

#+INCLUDE: "./footer.html" export html
