#+title: About Me
#+EXPORT_FILE_NAME: ../site/about.html
#+OPTIONS: toc:nil html-postamble:nil html-preamble:nil title:nil html-style:nil
#+HTML_HEAD: <link rel="stylesheet" href="static/styles.css"></link>
#+BEGIN_EXPORT html
<big><a href="index.html">Dhruva Kashyap</a></big>
<div class="main">
    <h2 style="">About Me</h2>
    <br /><br />
    <div class="pages">
    Hello there, I'm Dhruva Kashyap. My pronouns are He/Him. I was born in Bengaluru(ಬೆಂಗಳೂರು), India, and have lived here all my life.
    <br /><br />
    I am very passionate about Computer Science, a field of study that has taught me much.
    I finished my Undergraduate Bachelor's degree in Computer Science and Engineering from <a href="https://pes.edu">PES University</a>.
    As of writing this(December 2022), I am pursuing a Master's in Computer Science and Engineering from CSA, <a href="https://iisc.ac.in">IISc</a>.
    <br /><br />
    This is the <a href="static/gpg.txt" title="GPG Key">GPG Key</a> that I am currently using. Please manage your keys well. Read the <a href="https://www.gnupg.org/gph/en/manual.html">GNU Privacy Handbook</a> to learn more.
    <br /><br />
    I use <a href="https://github.com/hlissner/doom-emacs">Doom Emacs</a> to write everything you have seen. Many thanks, Henrik!
    <br /><br />
    I believe in the principles of the Free and Open Source Movement. The <a href="https://www.gnu.org/">GNU Project</a> and <a href="https://www.linuxfoundation.org/">Linux Foundation</a> are the cornerstone of modern software development.
    <br /><br />
    I have many favorite places for food around Bengaluru, but I am a
    vegetarian, so my recommendations will reflect that. This list is really sparse; please help me expand it!
    <ul>
        <li><a href="https://en.wikipedia.org/wiki/Central_Tiffin_Room_Bangalore">CTR, Malleshwaram</a></li>
        <li><a href="https://www.mavallitiffinrooms.com/">MTR, Lalbagh</a></li>
        <li>Umesh Dosa point, Sheshadripuram</li>
    </ul>
    I have many fond memories of being read stories by my grandparents. I have been reading for as long as I remember. A few books I can
    recommend(Again, a list that I definitely need to make longer):
    <ul>
        <li>Crime and Punishment, by Fyodor Dostoevsky</li>
        <li>Fahrenheit 451, by Ray Bradbury</li>
        <li>Outliers, by Malcolm Gladwell</li>
        <li>Lone wolf and Cub(子連れ狼), by writer Kazuo Koike and artist Goseki Kojima</li>
    </ul>
    I also love watching the cinema. Some of my favorite Directors are Francis Ford Coppola, Stanley Kubrick, Akira Kurosawa, George Lucas,
    Martin Scorsese, Steven Spielberg, Bong Joon-Ho, Alfred Hitchcock, Katheryn Bigelow, Quentin Tarantino, Hayao Miyazaki, and many more. I talk more <a href="blogs/movies.html">here.</a>
    <br /><br />
    I am a big fan of Star Wars. A character I really like is <a href="blogs/star_wars.html" style="color: inherit; text-decoration:none">Admiral Raddus</a>, who made his appearance in "Rogue One: A Star Wars Story."
    </div>
    <br /><br />
</div>
#+END_EXPORT

#+INCLUDE: "footer.html" export html
