#+TITLE: Why is this Web Site so bad?
#+EXPORT_FILE_NAME: ../website.html
#+OPTIONS: toc:nil html-postamble:nil html-preamble:nil title:nil html-style:nil
#+HTML_HEAD: <link rel="stylesheet" href="static/styles.css" />

* Between a rock and a hard place

I had an excellent teacher teach me HTML. I was a bad student is all.
I find it a fickle creature to tame. I had the choice of using static site generators, but I just wasn't happy using them. I was not going to use JS Frameworks because I wanted nothing to do with npm. The [[https://en.wikipedia.org/wiki/Npm_(software)][Wikipedia article on NPM]] has a section titled Notable Breakages. After many hours of thought, I felt that some good old HTML and a little bit of CSS was more than enough.

* The dark

The dark theme was a personal touch. Although I cannot help myself from being glued to a screen most of the day, I find it more comfortable if the screens are darker.

* Green?

Why are the links green? I like green.

* Marquee much?

I felt all the pages should have a common banner at the end. And I felt the marquee tag has felt enough damage. The plea for open source developers came from me watching many interesting talks from Benno Rice. Especially his talk on [[https://www.youtube.com/watch?v=BCqGjGzWI48][The New COBOL]].

* What font is this?

Cool, Isn't it? All credits to Professor Vinod Ganapathy at IISc[https://csa.iisc.ac.in/~vg]. I got the font from his page.

#+INCLUDE: "footer.html" export html
